// Data constants - moved from JS file

import type {
  Concern,
  Area,
  SkinTypeData,
  NotSureQuestion,
  FormStep,
} from "../types";

export const FORM_STEPS: FormStep[] = [
  "concerns",
  "areas",
  "age",
  "skinType",
  "skinTone",
  "ethnicBackground",
];
export const REQUIRED_STEPS: FormStep[] = [
  "concerns",
  "areas",
  "age",
  "skinType",
  "skinTone",
];
export const OPTIONAL_STEPS: FormStep[] = ["ethnicBackground"];

export const HIGH_LEVEL_CONCERNS: Concern[] = [
  {
    id: "facial-asymmetry",
    name: "Facial Asymmetry",
    description: "Correct uneven or asymmetrical facial features",
    mapsToPhotos: [
      "facial-asymmetry",
      "asymmetry",
      "asymmetric",
      "asymmetrical",
      "brow-asymmetry",
      "brow-balance",
      "balance-brow",
      "balance-brows",
      "resolve-brow",
      "asymmetric-brow",
      "asymmetric-brows",
      "brow-lift",
      "asymmetric-lips",
      "asymmetric-lip",
      "asymmetric-chin",
      "asymmetric-jawline",
      "resolve-asymmetry",
      "correct-asymmetry",
      "symmetry",
      "facial-symmetry",
    ],
    mapsToSpecificIssues: [
      "facial-asymmetry",
      "brow-asymmetry",
      "asymmetric-brow",
      "asymmetric-brows",
      "asymmetric-lips",
      "asymmetric-chin",
      "asymmetric-jawline",
    ],
  },
  {
    id: "facial-structure",
    name: "Facial Structure",
    description: "Enhance facial shape, definition, and structural features",
    mapsToPhotos: [
      "facial-balancing",
      "facial-harmony",
      "proportions",
      "balance",
      "balanced",
      "balancing",
      "harmony",
      "crooked-nose",
      "droopy-tip",
      "tip-droop-when-smiling",
      "dorsal-hump",
      "nasal-tip",
      "nose-rotation",
      "retruded-chin",
      "thin-lips",
      "long-philtral-column",
      "philtral",
      "masseter-hypertrophy",
      "wide-chin",
      "over-projected",
      "under-rotated",
    ],
    mapsToSpecificIssues: [
      "crooked-nose",
      "droopy-tip",
      "tip-droop-when-smiling",
      "dorsal-hump",
      "nasal-tip-too-narrow",
      "retruded-chin",
      "thin-lips",
      "long-philtral-column",
      "masseter-hypertrophy",
      "wide-chin",
      "over-projected-chin",
      "under-rotated",
      "proportions",
      "harmony",
    ],
  },
  {
    id: "skin-texture",
    name: "Skin Texture",
    description: "Improve skin smoothness, texture, and reduce scars",
    mapsToPhotos: [
      "texture",
      "smoothness",
      "roughness",
      "uneven-texture",
      "bumpy-skin",
      "improve-skin-texture",
      "skin-texture",
      "pores",
      "large-pores",
      "enlarged-pores",
      "refine-pores",
      "dull-skin",
      "rough-skin",
      "acne-scars",
      "acne-scarring",
      "scarring",
      "scars",
      "pitted",
      "ice-pick-scars",
      "boxcar-scars",
      "rolling-scars",
      "dry-skin",
      "oily-skin",
      "whiteheads",
      "blackheads",
      "crepey-skin",
      "unwanted-hair",
      "dry-lips",
    ],
    mapsToSpecificIssues: [
      "texture",
      "smoothness",
      "roughness",
      "uneven-texture",
      "bumpy-skin",
      "large-pores",
      "enlarged-pores",
      "visible-pores",
      "dull-skin",
      "rough-skin",
      "scars",
      "acne-scars",
      "ice-pick-scars",
      "boxcar-scars",
      "rolling-scars",
      "blackheads",
      "whiteheads",
      "dry-skin",
      "oily-skin",
      "crepey-skin",
      "unwanted-hair",
      "dry-lips",
    ],
  },
  {
    id: "fine-lines-wrinkles",
    name: "Fine Lines & Wrinkles",
    description: "Reduce visible lines and wrinkles",
    mapsToPhotos: ["wrinkles", "fine-lines", "aging", "lines", "forehead-lines", "glabella", "11s", "crow-feet"],
    mapsToSpecificIssues: [
      "wrinkles",
      "fine-lines",
      "crow's-feet",
      "forehead-lines",
      "glabella",
      "11s",
      "nasolabial-folds",
      "marionette-lines",
      "frown-lines",
      "under-eye-wrinkles",
      "perioral-wrinkles",
      "bunny-lines",
      "neck-lines",
    ],
  },
  {
    id: "skin-laxity",
    name: "Skin Laxity",
    description: "Tighten and lift drooping or excess skin",
    mapsToPhotos: [
      "sagging",
      "loose-skin",
      "drooping",
      "skin-laxity",
      "jowls",
      "neck-sagging",
      "brow-ptosis",
      "brow-droop",
      "excess-upper-eyelid-skin",
      "excess-lower-eyelid-skin",
      "upper-eyelid-droop",
      "lower-eyelid-sag",
      "lower-eyelid-bags",
      "prejowl-sulcus",
      "loose-neck-skin",
      "ill-defined-jawline",
    ],
    mapsToSpecificIssues: [
      "sagging-skin",
      "loose-skin",
      "jowls",
      "neck-sagging",
      "skin-laxity",
      "drooping",
      "brow-ptosis",
      "excess-upper-eyelid-skin",
      "excess-lower-eyelid-skin",
      "upper-eyelid-droop",
      "lower-eyelid-sag",
      "lower-eyelid-bags",
      "prejowl-sulcus",
      "loose-neck-skin",
      "ill-defined-jawline",
    ],
  },
  {
    id: "volume-loss",
    name: "Volume Loss",
    description: "Restore facial volume and fullness",
    mapsToPhotos: [
      "volume",
      "hollow",
      "deflated",
      "volume-loss",
      "temporal-hollow",
      "under-eye-hollow",
      "upper-eye-hollow",
      "mid-cheek-flattening",
      "cheekbone-not-prominent",
      "lacking-philtral-column",
      "gummy-smile",
      "lip-thinning-when-smiling",
      "lower-cheeks-volume-depletion",
      "platysmal-bands",
    ],
    mapsToSpecificIssues: [
      "volume-loss",
      "hollow-cheeks",
      "temple-hollowing",
      "temporal-hollow",
      "under-eye-hollows",
      "upper-eye-hollow",
      "mid-cheek-flattening",
      "cheekbone-not-prominent",
      "lacking-philtral-column",
      "gummy-smile",
      "lip-thinning-when-smiling",
      "lower-cheeks-volume-depletion",
      "platysmal-bands",
    ],
  },
  {
    id: "pigmentation",
    name: "Pigmentation",
    description: "Even out skin tone and reduce discoloration",
    mapsToPhotos: [
      "pigmentation",
      "discoloration",
      "dark-spots",
      "sun-damage",
      "red-spots",
      "under-eye-dark-circles",
    ],
    mapsToSpecificIssues: [
      "pigmentation",
      "dark-spots",
      "sun-spots",
      "melasma",
      "hyperpigmentation",
      "red-spots",
      "under-eye-dark-circles",
    ],
  },
  {
    id: "excess-fat",
    name: "Excess Fat",
    description: "Reduce unwanted fat and improve definition",
    mapsToPhotos: [
      "excess-fat",
      "submental-fullness",
      "stubborn-fat",
      "ill-defined-jawline",
      "double-chin",
    ],
    mapsToSpecificIssues: [
      "excess-fat",
      "submental-fullness",
      "stubborn-fat",
      "ill-defined-jawline",
      "double-chin",
    ],
  },
];

export const AREAS_OF_CONCERN: Area[] = [
  { id: "full-face", name: "Full Face" },
  { id: "forehead", name: "Forehead" },
  { id: "eyes", name: "Eyes" },
  { id: "cheeks", name: "Cheeks" },
  { id: "nose", name: "Nose" },
  { id: "mouth-lips", name: "Lips" },
  { id: "jawline", name: "Jawline" },
  { id: "chin", name: "Chin" },
  { id: "neck", name: "Neck" },
  { id: "chest", name: "Chest" },
  { id: "hands", name: "Hands" },
  { id: "arms", name: "Arms" },
  { id: "body", name: "Body" },
];

export const SKIN_TYPE_DATA: Record<string, SkinTypeData> = {
  dry: {
    title: "Dry",
    description:
      "Skin that lacks sufficient moisture and natural oils. It may feel tight, especially after cleansing, and can appear flaky or have a rough texture. Dry skin often shows fine lines more prominently and may have a dull appearance.",
    characteristics: [
      "Requires frequent moisturizing",
      "Visible fine lines",
      "Rough, uneven texture",
      "Dull appearance",
      "Flaky and tight",
    ],
  },
  balanced: {
    title: "Balanced",
    description:
      "Skin that has a good balance of moisture and oil. It feels comfortable, not too oily or too dry, and typically has an even texture and tone. Balanced skin usually has minimal visible pores and good elasticity.",
    characteristics: [
      "Even skin texture and tone",
      "Not too oily nor too dry",
      "Blemish free",
      "Minimal visible pores",
      "Good elasticity",
    ],
  },
  oily: {
    title: "Oily",
    description:
      "Skin that produces excess sebum, giving it a shiny or greasy appearance, especially in the T-zone (forehead, nose, and chin). Oily skin often has enlarged pores and may be prone to blackheads and breakouts.",
    characteristics: [
      "Greasy appearance/texture",
      "Good tone",
      "Persistent Shine",
      "Prone to blackheads",
      "Prone to breakouts",
      "Enlarged pores",
    ],
  },
  combination: {
    title: "Combination",
    description:
      "Both oily and dry areas on the face. The T-zone, which includes the forehead, nose, and chin, tends to be oilier, while the cheeks and other areas may be drier.",
    characteristics: [
      "Oily and dry areas",
      "Dry, tight cheeks",
      "Oilier T-zone (forehead, nose, chin)",
      "Enlarged Pores and breakouts in T-zone",
    ],
  },
};

export const NOT_SURE_QUESTIONS: NotSureQuestion[] = [
  {
    question: "How does your skin feel after cleansing?",
    subtitle: "Let's figure out your skin type!",
    options: [
      "It feels oily and/or shiny all over",
      "Shiny/oily in the T-zone (nose and forehead), dry/dull elsewhere",
      "Comfortable and balanced, no excessive oiliness or dryness",
      "It feels tight, dry, or flaky",
      "I'm not sure",
    ],
  },
  {
    question: "Which of these best describes your skin?",
    subtitle: "Just a few more details to find your skin type.",
    options: [
      "Enlarged pores, especially on the T-zone",
      "Dull complexion, rough texture",
      "Occasional breakouts but generally clear",
      "Oily T-zone with dry cheeks",
      "None of these describe my skin",
    ],
  },
];

export const AGE_RANGES = ["18-29", "30-39", "40-49", "50-59", "60+"] as const;
export const SKIN_TONES = [
  "light",
  "fair",
  "medium",
  "tan",
  "brown",
  "deep",
] as const;
export const ETHNIC_BACKGROUNDS = [
  "asian",
  "black",
  "hispanic/latino",
  "middle eastern",
  "white",
  "mixed",
  "other",
  "prefer-not-to-say",
] as const;
